Final Version of the NewsWeek Clone
Spayco/NewsWeek-Clone pull request #3
Opened 2020-02-13 15:01 UTC by Spayco

## Building with Backgrounds and Gradients : Apple Clone
- Added a Navigation Bar 
- Added Main Page
- Added a Footer
- Used Bootstrap classes
- No linter issue
- No HTML issues

[Live Version](https://raw.githack.com/Spayco/NewsWeek-Clone/feature/index.html)

2020-02-13 18:43 UTC, euqueme requested changes
> ### Pull Request Under the review by Maria Eugenia Queme P. (TSE)

### Hello @Spayco :handshake: 

### Your page looks very similar to the original and that deserves recognition :medal_sports: there are some key changes to make still :key: :construction_worker_man: 

## Small screens

**Section Positioning**

- [x] please follow the structure for the first 4 sections in this screen size:

1. TOP STORY
2. MORE STORIES
3. CULTURE & TRAVEL
4. FEATURED STORIES

- Yours

![image](https://user-images.githubusercontent.com/52209067/74463049-ce172a00-4e56-11ea-89d3-230e5613bc32.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74462967-b17af200-4e56-11ea-9db1-8326638e09e6.png)

**MORE STORIES**

- [x] the articles have to take 60% of the screen width and the title and content only 40%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74463297-4251cd80-4e57-11ea-9ddf-d3e769989507.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74463349-55649d80-4e57-11ea-8263-2e9e84607c5e.png)

**LATEST NEWS**

- [x] the articles have to take 60% of the screen width and the title and content only 40%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74463674-cc9a3180-4e57-11ea-8653-83dada48ae7e.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74463716-db80e400-4e57-11ea-80dd-a6ab87329371.png)

**IN THE MAGAZINE**

- [x] the IN THE MAGAZINE title is overlapping with the preview magazine lets fix it!

- Yours

![image](https://user-images.githubusercontent.com/52209067/74463887-2995e780-4e58-11ea-9045-980a53709310.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74463922-3ca8b780-4e58-11ea-89ea-b47f7fd90ca9.png)

- [x] The articles have to take 100% of the screen's width, yours seem to have big white spaces on the sides, also they should have some more spacing in between them

- Yours

![image](https://user-images.githubusercontent.com/52209067/74464406-15061f00-4e59-11ea-8ac7-41f6cff55d21.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74464454-28b18580-4e59-11ea-88fb-78eb52a95c2c.png)

**U.S, World, Business, Tech & Science, Culture and Sports**

- [x] The image of the aside articles of these sections should take 60% of the screen width and the headline only 40%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74464933-1552ea00-4e5a-11ea-89bf-4c9848a6c79e.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74464976-26036000-4e5a-11ea-9035-3061b1c5b453.png)

**SUBSCRIBE**

- [x] the preview magazines should be centered and the headline, paragraph, and button should come after and also horizontally centered

- Yours 

![image](https://user-images.githubusercontent.com/52209067/74465186-8d211480-4e5a-11ea-94f8-7df72af81e40.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74465209-99a56d00-4e5a-11ea-810d-44c0c5cb642f.png)

## Medium Screens

**Section Positioning**

- [x] please follow the structure of the 2 columns for the first 4 sections in this screen size:

         LEFT                                                           RIGHT
1. FEATURE STORIES                          |   TOP STORY
2. FEATURE STORIES (more articles)  |   CULTURE & TRAVEL
3. SPONSORED INSIGHT                     |   MORE STORIES

- Yours

![image](https://user-images.githubusercontent.com/52209067/74466238-72e83600-4e5c-11ea-9575-6dc8c6859fea.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74466287-83001580-4e5c-11ea-9bd2-b891af2e9e7e.png)

## Big Screens

**Editor's Pick**

- [x] The articles should be split into 4 columns instead of 2

- Yours

![image](https://user-images.githubusercontent.com/52209067/74466473-dffbcb80-4e5c-11ea-9d37-0619cbe4faa0.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74466501-edb15100-4e5c-11ea-8259-a22813aa9539.png)

## All sizes

**Footer**

- [x] remove the text "git" on the top of the NEWSWEEK logo

- Yours
![image](https://user-images.githubusercontent.com/52209067/74465321-cb1e3880-4e5a-11ea-8f35-bceb508dc221.png)

- Original
![image](https://user-images.githubusercontent.com/52209067/74465352-d96c5480-4e5a-11ea-9761-332d0200fbbf.png)

## Bootstrap usage

- [x] This project is all about using bootstrap, use bootstrap everywhere for the new changes and replace these selectors in your CSS file

- padding: 0; (12 ocurrences )
- padding-left: 0; (1 ocurrences )
- padding-right: 0; (1 ocurrences )
- margin: 0; (8 ocurrences )
- margin-left: 0; (4 ocurrences )
- margin-right: 0 (2 ocurrences )
- margin-top: 0 (2 ocurrences )
- margin-bottom: 0 (1 ocurrences )
- color: black; (8 ocurrences in yor CSS file)
- color: white; (10 ocurrences )
- text-align: center; (2 ocurrences )
- background-color: white; (4 ocurrence )
- display: none; (1 ocurrences )
- text-decoration: none; (15 ocurrences)
- font-weight (28 occurrences, strongly recommend not using the number values and use the bootstrap classes instead)

### That's it! :raised_hands: 

### Please :pray:  do these changes :memo: and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

Any question? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-13 18:43 UTC, euqueme commented on Media/main.css
> +}
please don't use this fix (from line #14 to #18) :no_good_woman:  instead use bootstrap classes for **margin-left: 0**; and **margin-right: 0**; every where you use the **.row** class in yor HTML file

2020-02-14 10:15 UTC, Spayco commented on Media/main.css
> +}
done!

2020-02-14 12:07 UTC, Spayco commented
hey, i fixed everything you mentioned, hopefully i didn't miss something! 
one note though, you might find to `margin: 0;` because i used `margin: 0 auto;` to center, i googled and didn't find any class like it on bootstrap

2020-02-14 17:59 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-14 17:59 UTC, pelzolga123 commented
## Hi Spayco! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: great!
But still next parts look not like original:
* [ ] Small version:
![image](https://user-images.githubusercontent.com/20416431/74554521-6c43e680-4f62-11ea-9a63-adce66c1dfac.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/74554581-8bdb0f00-4f62-11ea-8dd3-60d405721a12.png)
* [Optional] Take a look how each section is aligned after another. Your project will look much better if you will align all sections properly:
![image](https://user-images.githubusercontent.com/20416431/74554728-de1c3000-4f62-11ea-8db7-877a239b8d39.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/74554808-0dcb3800-4f63-11ea-9017-d73d1ff5c019.png)
* [ ] Tablet version:
Next part looks weird, that needs to be fixed:
![image](https://user-images.githubusercontent.com/20416431/74555291-17a16b00-4f64-11ea-8638-8005891d1be9.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/74555400-4f101780-4f64-11ea-8606-e0a81c1427aa.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-16 23:08 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-02-16 23:24 UTC, kobiyoyo requested changes
## Hi @Spayco      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there is one  more thing required. 
### General
###### Small Screen
- [x] The ***Top Story Section***  should look more like the original (Give it padding)  & the ***Sign in & Subscribe button*** should be positioned well.
Your Version
![1](https://user-images.githubusercontent.com/23278161/74614812-9c82b500-511b-11ea-8891-1d73062af1af.png)

Original Version

![2](https://user-images.githubusercontent.com/23278161/74614817-a60c1d00-511b-11ea-9891-babe3284eb96.png)

.



 

### Make changes and submit another code review request.
*Happy coding*

2020-02-17 10:47 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback

2020-02-17 11:08 UTC, Oluwadamilareolusakin commented
# Great job building this @Spayco!
It's all coming together pretty nicely and you've worked hard to try to implement the requested changes :ok_hand: Please consider my comments below along with the attached screenshots on the changes I'm proposing

#### Responsiveness
The major issues with the project currently, revolve around responsiveness and the following sections need a thorough inspection:

* Navigation
Please consider looking into the navigation bar on mobile screens, it's a bit disorganized at the moment, I've attached a screenshot below, please compare yours with the original at 320px
![screenshot](https://images2.imgbox.com/5d/ec/JYVrBMyS_o.png)
![screenshot](https://images2.imgbox.com/ce/46/BcUCB8m5_o.png)

* Top Story
Please consider looking into the padding in the top story section of the page, compare yours with the original page's and you may find that it isn't supposed to sit smack on the edges of the browser pane on mobile screens
![screenshot](https://images2.imgbox.com/3b/43/xTZJ417M_o.png)

* Footer
Please consider the following screenshot in conjunction with what is present on the original site, you may find that there needs to be a little more space between the Newsweek logo and social icons
![screenshot](https://images2.imgbox.com/5d/ec/JYVrBMyS_o.png)

* Subscribe Section
Please consider the following section in the screenshot below, comparing it with that of the original page, you may find some discrepancies in the responsiveness of the image. Please consider making the appropriate changes

### Summary
You have done a great job building this out, please consider my comments above, make the required changes and request another review. I wish you the best in all your endeavors! :rocket: See you at the top :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-17 12:54 UTC, Spayco commented
fixed all the issues, 
if there's anything else that I need to change, please let me know, applying for another review

2020-02-17 13:01 UTC, nikasulo approved these changes
# Really awesome job! @Spayco 
You may merge this and keep going :handshake: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-17 13:04 UTC, merged